server:
  port: 5551

spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pubsub
    username: postgres
    password: root
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: create-drop